# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x1a\x0c\x63ommon.proto\"7\n\x0b\x42ookingData\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x18\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\t.DateData\"1\n\tMovieData\x12\x0f\n\x07movieId\x18\x01 \x01(\t\x12\x13\n\x0bseatsBooked\x18\x02 \x01(\x05\"8\n\x08\x44\x61teData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1e\n\nmoviesData\x18\x02 \x03(\x0b\x32\n.MovieData\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\"M\n\x11\x43reateBookingData\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\r\n\x05movie\x18\x03 \x01(\t\x12\r\n\x05seats\x18\x04 \x01(\x05\"U\n\x11\x44\x65leteBookingData\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\r\n\x05movie\x18\x03 \x01(\t\x12\x15\n\rseatsToDelete\x18\x04 \x01(\x05\"L\n\x15\x43reateBookingResponse\x12\x1b\n\x08response\x18\x01 \x01(\x0b\x32\t.Response\x12\x16\n\x0eremainingSeats\x18\x02 \x01(\x05\"L\n\x15\x44\x65leteBookingResponse\x12\x1b\n\x08response\x18\x01 \x01(\x0b\x32\t.Response\x12\x16\n\x0eremainingSeats\x18\x02 \x01(\x05\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x91\x02\n\x07\x42ooking\x12(\n\x0eGetAllBookings\x12\x06.Empty\x1a\x0c.BookingData0\x01\x12*\n\x11GetBookingsOfUser\x12\x07.UserId\x1a\x0c.BookingData\x12\x36\n\x15GetBookingsOfShowtime\x12\r.ShowtimeData\x1a\x0c.BookingData0\x01\x12;\n\rCreateBooking\x12\x12.CreateBookingData\x1a\x16.CreateBookingResponse\x12;\n\rDeleteBooking\x12\x12.DeleteBookingData\x1a\x16.DeleteBookingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKINGDATA']._serialized_start=31
  _globals['_BOOKINGDATA']._serialized_end=86
  _globals['_MOVIEDATA']._serialized_start=88
  _globals['_MOVIEDATA']._serialized_end=137
  _globals['_DATEDATA']._serialized_start=139
  _globals['_DATEDATA']._serialized_end=195
  _globals['_USERID']._serialized_start=197
  _globals['_USERID']._serialized_end=217
  _globals['_CREATEBOOKINGDATA']._serialized_start=219
  _globals['_CREATEBOOKINGDATA']._serialized_end=296
  _globals['_DELETEBOOKINGDATA']._serialized_start=298
  _globals['_DELETEBOOKINGDATA']._serialized_end=383
  _globals['_CREATEBOOKINGRESPONSE']._serialized_start=385
  _globals['_CREATEBOOKINGRESPONSE']._serialized_end=461
  _globals['_DELETEBOOKINGRESPONSE']._serialized_start=463
  _globals['_DELETEBOOKINGRESPONSE']._serialized_end=539
  _globals['_RESPONSE']._serialized_start=541
  _globals['_RESPONSE']._serialized_end=585
  _globals['_BOOKING']._serialized_start=588
  _globals['_BOOKING']._serialized_end=861
# @@protoc_insertion_point(module_scope)
