# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"7\n\x0b\x42ookingData\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x18\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\t.DateData\"1\n\tMovieData\x12\x0f\n\x07movieId\x18\x01 \x01(\t\x12\x13\n\x0bseatsBooked\x18\x02 \x01(\x05\"8\n\x08\x44\x61teData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1e\n\nmoviesData\x18\x02 \x03(\x0b\x32\n.MovieData\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x08Showtime\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05movie\x18\x02 \x01(\t\"M\n\x11\x43reateBookingData\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\r\n\x05movie\x18\x03 \x01(\t\x12\r\n\x05seats\x18\x04 \x01(\x05\"U\n\x11\x44\x65leteBookingData\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\r\n\x05movie\x18\x03 \x01(\t\x12\x15\n\rseatsToDelete\x18\x04 \x01(\x05\"\x07\n\x05\x45mpty\"L\n\x15\x43reateBookingResponse\x12\x1b\n\x08response\x18\x01 \x01(\x0b\x32\t.Response\x12\x16\n\x0eremainingSeats\x18\x02 \x01(\x05\"L\n\x15\x44\x65leteBookingResponse\x12\x1b\n\x08response\x18\x01 \x01(\x0b\x32\t.Response\x12\x16\n\x0eremainingSeats\x18\x02 \x01(\x05\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8d\x02\n\x07\x42ooking\x12(\n\x0eGetAllBookings\x12\x06.Empty\x1a\x0c.BookingData0\x01\x12*\n\x11GetBookingsOfUser\x12\x07.UserId\x1a\x0c.BookingData\x12\x32\n\x15GetBookingsOfShowtime\x12\t.Showtime\x1a\x0c.BookingData0\x01\x12;\n\rCreateBooking\x12\x12.CreateBookingData\x1a\x16.CreateBookingResponse\x12;\n\rDeleteBooking\x12\x12.DeleteBookingData\x1a\x16.DeleteBookingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKINGDATA']._serialized_start=17
  _globals['_BOOKINGDATA']._serialized_end=72
  _globals['_MOVIEDATA']._serialized_start=74
  _globals['_MOVIEDATA']._serialized_end=123
  _globals['_DATEDATA']._serialized_start=125
  _globals['_DATEDATA']._serialized_end=181
  _globals['_USERID']._serialized_start=183
  _globals['_USERID']._serialized_end=203
  _globals['_SHOWTIME']._serialized_start=205
  _globals['_SHOWTIME']._serialized_end=244
  _globals['_CREATEBOOKINGDATA']._serialized_start=246
  _globals['_CREATEBOOKINGDATA']._serialized_end=323
  _globals['_DELETEBOOKINGDATA']._serialized_start=325
  _globals['_DELETEBOOKINGDATA']._serialized_end=410
  _globals['_EMPTY']._serialized_start=412
  _globals['_EMPTY']._serialized_end=419
  _globals['_CREATEBOOKINGRESPONSE']._serialized_start=421
  _globals['_CREATEBOOKINGRESPONSE']._serialized_end=497
  _globals['_DELETEBOOKINGRESPONSE']._serialized_start=499
  _globals['_DELETEBOOKINGRESPONSE']._serialized_end=575
  _globals['_RESPONSE']._serialized_start=577
  _globals['_RESPONSE']._serialized_end=621
  _globals['_BOOKING']._serialized_start=624
  _globals['_BOOKING']._serialized_end=893
# @@protoc_insertion_point(module_scope)
